{% set version = datetime.datetime.utcnow().strftime('%Y%m%d.%H.%M.%S') %}

package:
  name: conda-forge-repodata-patches
  version: {{ version }}

source:
  path: .

build:
  noarch: generic
  number: 0
  script:
    - "yamllint -d '{extends: default, rules: {document-start: disable, line-length: {max: 120}}}' patch_yaml/."
    - black --check patch_yaml_utils.py
    - ruff patch_yaml_utils.py
    - black --check patch_yaml_model.py
    - ruff patch_yaml_model.py
    - black --check test_patch_yaml_utils.py
    - ruff test_patch_yaml_utils.py
    - pytest -vv test_patch_yaml_utils.py
    - pytest -vv test_gen_patch_json.py
    - python gen_patch_json.py

requirements:
  build:
    - python 3.11.*
    - requests
    - tqdm
    - license-expression
    - packaging
    - pyyaml
    - pydantic
    - black
    - ruff
    - pytest
    - yamllint
  host:
  run:

test:
  files:
    - test_gen_patch_json.py
    - gen_patch_json.py
    - get_license_family.py
    - show_diff.py
    - patch_yaml_model.json
    - patch_yaml_model.py
    - patch_yaml_utils.py
    - patch_yaml
    - test_patch_yaml_utils.py
  requires:
    - python 3.*
    - requests
    - packaging
    - tqdm
    - license-expression
    - pyyaml
    - pydantic
    - conda-build
    - pytest
    - yamllint
  commands:
    {% for subdir in ("noarch", "linux-64", "linux-armv7l", "linux-ppc64le", "osx-64", "osx-arm64", "win-32", "win-64") %}
    - test -e $PREFIX/{{ subdir }}/patch_instructions.json
    {% endfor %}
    - python show_diff.py

about:
  summary: generate tweaks to index metadata, hosted separately from anaconda.org index
  home: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock
  license: CC-PDDC
  description: |
    See the [recipe/patch_yaml/README.md](recipe/patch_yaml/README.md) for how generate patches from static YAML files.
    This mechanism should work for most things. If it does not work for your specific case, you
    can write custom code in `generate_patch_json.py`.

extra:
  recipe-maintainers:
    - conda-forge/core
