package:
  name: conda-forge-repodata-patches
  version: 20191026

source:
  path: .

build:
  noarch: generic
  number: 0
  script:
    - python gen_patch_json.py

requirements:
  build:
    - python 3.*
    - requests
    - tqdm

test:
  files:
    - test_gen_patch_json.py
    - gen_patch_json.py
  requires:
    - python 3.*
    - requests
    - tqdm
    - pytest
  commands:
    {% for subdir in ("noarch", "linux-64", "linux-armv7l", "linux-ppc64le", "osx-64", "win-32", "win-64") %}
    - test -e $PREFIX/{{ subdir }}/patch_instructions.json
    {% endfor %}
    - pytest -vv test_gen_patch_json.py

about:
  summary: generate tweaks to index metadata, hosted separately from anaconda.org index
  home: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock
  license: Public Domain

extra:
  recipe-maintainers:
    - conda-forge/core
