{% set version = datetime.datetime.utcnow().strftime('%Y%m%d.%H.%M.%S') %}

package:
  name: conda-forge-repodata-patches
  version: {{ version }}

source:
  path: .

build:
  noarch: generic
  number: 0
  script:
    - python gen_patch_json.py

requirements:
  build:
    - python 3.*
    - setuptools <66.0.0a
    - requests
    - tqdm
    - license-expression
    - packaging
  host:
  run:

test:
  files:
    - test_gen_patch_json.py
    - gen_patch_json.py
    - get_license_family.py
    - show_diff.py
  requires:
    - python 3.*
    - setuptools <66.0.0a
    - requests
    - tqdm
    - license-expression
    - pytest
    - conda-build
  commands:
    {% for subdir in ("noarch", "linux-64", "linux-armv7l", "linux-ppc64le", "osx-64", "osx-arm64", "win-32", "win-64") %}
    - test -e $PREFIX/{{ subdir }}/patch_instructions.json
    {% endfor %}
    - pytest -vv test_gen_patch_json.py
    - python show_diff.py

about:
  summary: generate tweaks to index metadata, hosted separately from anaconda.org index
  home: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock
  license: CC-PDDC

extra:
  recipe-maintainers:
    - conda-forge/core
