appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: fZaJUdX6gbkZD/rC84QXF6EZl9znLLusdAKVzYYWnMjsCxILqbIuVXrLdgL9vZDdvmt1PUWRt+6GQni86d1ayE92s3e18Psi/QvTg5EviBCpvfOQiyZ/8ldHEok7mpdM/nO5ZLRyzEykNk1E0ThFtMj2jTF+BnfGB9v5TjBeyf0Tinlaj8OFBj+/m7uWnyCtcHFxnXpt8KAaSvjwG51dz1rme8fTaoaIpOfIff+MAkD+z6StY4wqu2IhZfa7N+0BPIKNC0xvuPoKzt1zDyo35kXvgrIXNSSiqWdnyeu+Rty12iV/wqwfk4Dda55FSoYxXVDjkNQFjMSMlg7AeL7ghKkLafusA86FMowpeQQm8WK98Ahzj4pNc+l6MhRHoQkYxcfabJx8e/pdnijSSw+8TlItguiAzegpr3905M5vmmznC8VpZTVYmuUQitB7UU0yN0K4GGdh85ei9NnlwrQHoReHPqUCvTHDPgfjMAnGPWAevhRIYWZXHghwfjzunW98dmsu4aNMe8B9Rt3TBsKwFVJ4ogpJOIUtmgdX8YMoXahR6Cl8bVJIdC21SjCgSO8sl6cLnz2pd8KVrVqkmjmwfGmmfse8bWiUQd17HFUhh0sKMbt/MIVAzT4cBkvVxfSSO73Xx5Y1tl7nMphQsW4nyBtiu9gFQzcI+tbUCQLsm3E=}
