# yaml-language-server: $schema=../patch_yaml_model.json
# if record_name == "conda-build":
#     # Code removed in conda 4.13.0 broke older conda-build releases;
#     # x-ref issue: conda/conda-build#4481
#     if (
#         parse_version(record["version"]) <=
#         parse_version("3.21.7") or
#         # backported fix in 3.21.8, build 1
#         # (PR: conda-forge/conda-build-feedstock#176)
#         record["version"] == "3.21.8" and record["build_number"] == 0
#     ):
#         for i, dep in enumerate(record["depends"]):
#             dep_name, *dep_other = dep.split()
#             if dep_name == "conda" and ",<" not in dep:
#                 record["depends"][i] = "{} {}<4.13.0".format(
#                     dep_name, dep_other[0] + "," if dep_other else ""
#                 )
if:
  name: conda-build
  version_le: "3.21.7"
then:
  - tighten_depends:
      name: conda
      upper_bound: "4.13.0"
---
if:
  name: conda-build
  version: "3.21.8"
  build_number: 0
then:
  - tighten_depends:
      name: conda
      upper_bound: "4.13.0"
---
#     # pin setuptools to <66 to avoid `parse_version` issues
#     # see https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/3973
#     if record.get("timestamp", 0) <= 1674131439051:  # 2023-01-19
#         for i, dep in enumerate(record["depends"]):
#             dep_name, *dep_other = dep.split()
#             if dep_name == "setuptools" and ",<" not in dep:
#                 record["depends"][i] = "{} {}<66.0.0a0".format(
#                     dep_name, dep_other[0] + "," if dep_other else ""
#                 )
if:
  name: conda-build
  timestamp_le: 1674131439051  # 2023-01-19
then:
  - tighten_depends:
      name: setuptools
      upper_bound: "66.0.0a0"
---
#     # conda-build 3.26.x requires conda 23.7.x
#     if record["version"] in ("3.26.0", "3.26.1") and record.get("timestamp", 0) <= 16935094895456:
#         _replace_pin("conda >=4.13", "conda >=23.7.3", record["depends"], record)
if:
  name: conda-build
  version_in: ["3.26.0", "3.26.1"]
  timestamp_lt: 16935094895456  # 2023-08-31
then:
  - replace_depends:
      old: "conda >=4.13"
      new: "conda >=23.7.3"
