# from this bit of code
# if (
#     record_name == "conda"
#     and record["version"] == "22.11.1"
#     and record["build_number"] == 0
# ):
#     for i, dep in enumerate(record["constrains"]):
#         dep_name, *dep_other = dep.split()
#         if dep_name.startswith("conda-libmamba-solver"):
#             record["constrains"][i] = "conda-libmamba-solver >=22.12.0"
if:
  name: conda
  version: "22.11.1"
  build_number: 0
then:
  - replace_constrains:
      old: conda-libmamba-solver*
      new: conda-libmamba-solver >=22.12.0
---
# The lower bound on conda-libmamba-solver was increased for 25.1.0 in
# <https://github.com/conda/conda/commit/6db7b91585aa7e111f2df6565e7053b6234c0b3b>
# but not updated in conda-feedstock, leading to breakage described in
# <https://github.com/conda-forge/conda-feedstock/issues/259>.
# This was corrected in <https://github.com/conda-forge/conda-feedstock/pull/267>.
# There is a strange discrepancy with v25.3.1 having been published to conda-forge
# while the recipe was still on v25.3.0. I have inquired about this in
# <https://github.com/conda-forge/conda-feedstock/pull/266#issuecomment-2789657700>.
if:
  name: conda
  version_ge: "25.1.0"
  version_le: "25.3.1"
  timestamp_lt: 1744218305000
then:
  - add_depends: conda-libmamba-solver >=24.11.0
---
if:
  name: conda
  version_eq: 25.9.0
  timestamp_lt: 1759388400000
then:
  - replace_depends:
      old: conda-libmamba-solver >=24.11.0
      new: conda-libmamba-solver >=25.4.0
