# yaml-language-server: $schema=../patch_yaml_model.json
# if record_name == "conda-forge-ci-setup" and record.get('timestamp', 0) < 1638899810000:
#     constrains = record.get("constrains", [])
#     found = any(c.startswith("boa") for c in constrains)
#     if not found:
#         constrains.append("boa >=0.8,<0.9")
#     record["constrains"] = constrains
if:
  name: conda-forge-ci-setup
  timestamp_lt: 1638899810000
  not_has_constrains: "boa?( *)"
then:
  - add_constrains: "boa >=0.8,<0.9"