# from this code
# if record_name == "conda-build":
#     # Code removed in conda 4.13.0 broke older conda-build releases;
#     # x-ref issue: conda/conda-build#4481
#     if (
#         parse_version(record["version"]) <= parse_version("3.21.7")
#         or
#         # backported fix in 3.21.8, build 1
#         # (PR: conda-forge/conda-build-feedstock#176)
#         record["version"] == "3.21.8"
#         and record["build_number"] == 0
#     ):
#         for i, dep in enumerate(record["depends"]):
#             dep_name, *dep_other = dep.split()
#             if dep_name == "conda" and ",<" not in dep:
#                 record["depends"][i] = "{} {}<4.13.0".format(
#                     dep_name, dep_other[0] + "," if dep_other else ""
#                 )
#     # pin setuptools to <66 to avoid `parse_version` issues
#     # see https://github.com/conda-forge/
#     #   conda-forge-pinning-feedstock/issues/3973
#     if record.get("timestamp", 0) <= 1674131439051:  # 2023-01-19
#         for i, dep in enumerate(record["depends"]):
#             dep_name, *dep_other = dep.split()
#             if dep_name == "setuptools" and ",<" not in dep:
#                 record["depends"][i] = "{} {}<66.0.0a0".format(
#                     dep_name, dep_other[0] + "," if dep_other else ""
#                 )
if:
  name: conda-build
  version_le: 3.21.7
then:
  - tighten_depends:
      name: conda
      upper_bound: "4.13"
---
if:
  name: conda-build
  version: 3.21.8
  build_number: 0
then:
  - tighten_depends:
      name: conda
      upper_bound: "4.13"
---
if:
  name: conda-build
  timestamp_le: 1674131439051  # 2023-01-19
then:
  - tighten_depends:
      name: setuptools
      upper_bound: 66.0.0
---
# from this code
# if record_name == "conda-build":
#     # conda-build 3.26.x requires conda 23.7.x
#     if (
#         record["version"] in ("3.26.0", "3.26.1")
#         and record.get("timestamp", 0) <= 16935094895456
#     ):
#         _replace_pin(
#             "conda >=4.13", "conda >=23.7.3", record["depends"], record
#         )
if:
  name: conda-build
  version_in: [3.26.0, 3.26.1]
  timestamp_le: 16935094895456
then:
  - replace_depends:
      old: conda >=4.13
      new: conda >=23.7.3
---
# conda-build <3.25.0 relied on get_prfix removed in
# https://github.com/conda/conda/commit/a26db05d5abd10a251128e2ce5092e7e8bb72f46
if:
  name: conda-build
  version_lt: 3.25.0
then:
  - tighten_depends:
      name: conda
      upper_bound: 23.9.0
---
# conda.auxlib.packaging was removed in 24.3.0 but still neeeded by conda-build
# https://github.com/conda/conda-build/pull/5221
if:
  name: conda-build
  version_gt: 3.21.8
  version_lt: 24.3.0
  timestamp_le: 1710834612324  # 2024-03-19
then:
  - tighten_depends:
      name: conda
      upper_bound: 24.3.0
---
# https://github.com/conda/conda-build/issues/5227
if:
  name: conda-build
  version_lt: 24.3.0
  timestamp_le: 1711365884254  # 2024-03-25
then:
  - tighten_depends:
      name: py-lief
      upper_bound: "0.14"
---
# https://github.com/conda/conda-build/issues/5564
if:
  name: conda-build
  version_lt: 24.11.3
  timestamp_le: 1733914099000  # 2024-12-11
then:
  - tighten_depends:
      name: py-lief
      upper_bound: "0.15"
---
# https://github.com/conda/conda-build/issues/5594
if:
  name: conda-build
  version_le: 25.11.1
  timestamp_le: 1737049820000  # 2025-01-16
then:
  - tighten_depends:
      name: py-lief
      upper_bound: "0.15"
