# yaml-language-server: $schema=../patch_yaml_model.json
# if (record_name == "conda" and
#     record["version"] == "22.11.1" and
#     record["build_number"] == 0):
#     for i, dep in enumerate(record["constrains"]):
#         dep_name, *dep_other = dep.split()
#         if dep_name.startswith("conda-libmamba-solver"):
#             record["constrains"][i] = "conda-libmamba-solver >=22.12.0"
if:
  name: conda
  version: "22.11.1"
  build_number: 0
then:
  - replace_constrains:
      old: "conda-libmamba-solver?( *)"
      new: "conda-libmamba-solver >=22.12.0"
