# from this code
# if (
#     record_name == "conda-forge-ci-setup"
#     and record.get("timestamp", 0) < 1638899810000
# ):
#     constrains = record.get("constrains", [])
#     found = any(c.startswith("boa") for c in constrains)
#     if not found:
#         constrains.append("boa >=0.8,<0.9")
#     record["constrains"] = constrains
if:
  name: conda-forge-ci-setup
  timestamp_lt: 1638899810000
  not_has_constrains: boa*
then:
  - add_constrains: boa >=0.8,<0.9
---
# https://github.com/conda-forge/conda-forge.github.io/issues/2117
if:
  name: conda-forge-ci-setup
  timestamp_lt: 1710847759000
then:
  - tighten_depends:
      name: conda-build
      upper_bound: 24.5.0
---
if:
  name: conda-forge-ci-setup
  has_depends: rattler-build-conda-compat?( *)
  timestamp_lt: 1722516295000
then:
  - tighten_depends:
      name: rattler-build-conda-compat
      max_pin: "x"
